window.PORTFOLIO_CONFIG = {
  contactApiUrl: "https://YOUR-PYTHON-BACKEND/api/contact",
  DJANGO_PROJECT_URL: "",
  ROAD_ACCIDENT_REPOSITORY_URL: "",
  FRANCE_RELOCATION_REPOSITORY_URL: "",
  FRANCE_RELOCATION_DEMO_URL: "",
  WEATHER_DAGS_REPOSITORY_URL: "",
  ADMISSION_SERVICE_REPOSITORY_URL: "",
  LINKEDIN_PROFILE_URL: "",
  GITHUB_PROFILE_URL: "",
  X_PROFILE_URL: ""
};
